/* PRODUCT [START] */

export const FETCH_PRODUCT_START = 'FETCH_PRODUCT_START';
export const FETCH_PRODUCT_FAIL = 'FETCH_PRODUCT_FAIL';
export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS';

/* PRODUCT [END] */

/* CART [START] */

export const ADD_TO_CART_START = 'ADD_TO_CART_START';
export const ADD_TO_CART_FAIL = 'ADD_TO_CART_FAIL';
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';

export const REMOVE_FROM_CART_START = 'REMOVE_FROM_CART_START';
export const REMOVE_FROM_CART_FAIL = 'REMOVE_FROM_CART_FAIL';
export const REMOVE_FROM_CART_SUCCESS = 'REMOVE_FROM_CART_SUCCESS';

export const SUBSCRIBE_CART_START = 'SUBSCRIBE_CART_START';
export const SUBSCRIBE_CART_FAIL = 'SUBSCRIBE_CART_FAIL';
export const SUBSCRIBE_CART_SUCCESS = 'SUBSCRIBE_CART_SUCCESS';

export const UNSUBSCRIBE_CART = 'UNSUBSCRIBE_CART';

/* CART [END] */

/* WISHLIST [START] */

export const ADD_TO_WISHLIST_START = 'ADD_TO_WISHLIST_START';
export const ADD_TO_WISHLIST_FAIL = 'ADD_TO_WISHLIST_FAIL';
export const ADD_TO_WISHLIST_SUCCESS = 'ADD_TO_WISHLIST_SUCCESS';

export const REMOVE_FROM_WISHLIST_START = 'REMOVE_FROM_WISHLIST_START';
export const REMOVE_FROM_WISHLIST_FAIL = 'REMOVE_FROM_WISHLIST_FAIL';
export const REMOVE_FROM_WISHLIST_SUCCESS = 'REMOVE_FROM_WISHLIST_SUCCESS';

export const SUBSCRIBE_WISHLIST_START = 'SUBSCRIBE_WISHLIST_START';
export const SUBSCRIBE_WISHLIST_FAIL = 'SUBSCRIBE_WISHLIST_FAIL';
export const SUBSCRIBE_WISHLIST_SUCCESS = 'SUBSCRIBE_WISHLIST_SUCCESS';

export const UNSUBSCRIBE_WISHLIST = 'UNSUBSCRIBE_WISHLIST';

/* WISHLIST [END] */

/* LIST [START] */

export const FETCH_LIST_START = 'FETCH_LIST_START';
export const FETCH_LIST_FAIL = 'FETCH_LIST_FAIL';
export const FETCH_LIST_SUCCESS = 'FETCH_LIST_SUCCESS';

/* LIST [END] */

/* AUTH [START] */

export const SWITCH_SHOW_AUTH = 'SWITCH_SHOW_AUTH';
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';

export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';
export const SUBSCRIBE_AUTH_STATE = 'SUBSCRIBE_AUTH_STATE';
export const UNSUBSCRIBE_AUTH_STATE = 'UNSUBSCRIBE_AUTH_STATE';

/* AUTH [END] */

/* ERROR [START] */

export const ADD_ERROR = 'ADD_ERROR';
export const REMOVE_ERROR = 'REMOVE_ERROR';

/* ERROR [END] */
